import type { Metadata } from "next";
import "../assets/styles/globals.css";
import { sfProDisplay } from "@/shared/utils/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${sfProDisplay.variable}`}>{children}</body>
    </html>
  );
}
